@extends('layouts.main')

@section('title')
Different titles can go here.
@endsection

@section('content')
    <h1>Homepage</h1>
    <p>Content types:</p>
    <ul>
        <li>
            Page: (like a static Homepage, Contact, About page)
            <ul>
                <li>title<sup>*</sup></li>
                <li>intro paragraph? Thinking about the blue background on Mi<sup>2</sup></li>
                <ul><li>can also just use the abstract for this.</li></ul>
                <li>body<sup>*</sup></li>
                <li>abstract<sup>*</sup> (can be autogenerated if left empty)</li>
                <li>author<sup>*</sup> (must be logged in to create, so this is autofilled)</li>
                <li>images?</li>
                <li>Laravel takes care of timestamps...</li>
            </ul>
            First pass is implemented
            <ul>
                <li>Title and body are required</li>
                <li>Title and slug (if provided) must be unique</li>
                    <ul><li>See PageController for other validations</li></ul>
                <li>If slug is provided, on save, redirects to /page/[slug], else to /page/[id]</li>
                    <ul><li>these links aren't placed anywhere yet, so gotta find em thru SequelPro</li></ul>
                <li>Abstract takes first 30 (can be any number, just uses subst) characters from body - simple, but it works</li>
                <li>Timestamps, including soft deletes, added</li>
                    <ul><ul><li>really, only thing not implemented in some way is images</li></ul></ul>
            </ul>
            Next steps
            <ol>
                <li>Formatted text</li>
                    <ul><li>At least line breaks work.</li></ul>
                <li>images</li>
            </ol>
        </li>
        <li>
            Block:
            <ul>
                <li>area<sup>*</sup></li>
                    <ul><li>as in, area on the page</li></ul>
                <li>body<sup>*</sup></li>
                <li>weight</li>
                    <ul><li>will default to one of the dates if not supplied.</li></ul>
                <li>page_slug</li>
                    <ul>
                        <li>array</li>
                        <li>as in, which page slug the block belongs to.</li>
                    </ul>
                <li>author<sup>*</sup> (must be logged in to create, so this is autofilled)</li>
                <li>Laravel takes care of timestamps...</li>
            </ul>
            So far...
            <ul>
                <li>No forms for blocks yet</li>
                    <ul><li>for now, just create through SequelPro</li></ul>
                <li>area is working</li>
                    <ul><li>in PageController, loops thru all blocks fetched from page_slug, and creates a new Collection (actually Collection var type) and sorts them into separate arrays with the key of it's area. ... just go check it out, not super complicated</li></ul>
                <li>body is working, same as other bodies</li>
                <li>weight not implemented</li>
                <li>page_slug is working</li>
                    <ul>
                        <li>in the PageController, fetch any blocks with the page_slug property equal to the provided $page variable</li>
                        <li>still needs to be changed to array so blocks can be used multiple places</li>
                    </ul>
                <li>author not implemented</li>
            </ul>
        </li>
    </ul>
@endsection

@section('scripts')
    <script type="text/javascript">
    </script>
@endsection